using System;
using System.Collections.Generic;
using System.Globalization;

namespace BGCOP.CAVTOP.BUSINESSLAYER
{
	public class ModulosSoftware
	{
		public List<string> ListaModulos = new List<string>();

		public ModulosSoftware()
		{
			int num = 0;
			int num1 = num + 1;
			int num2 = num;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 1. Tipos de Identificacion"));
			int num3 = num1;
			num1 = num3 + 1;
			num2 = num3;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 2. Maestro de Cargos"));
			int num4 = num1;
			num1 = num4 + 1;
			num2 = num4;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 3. Maestro de Estados"));
			int num5 = num1;
			num1 = num5 + 1;
			num2 = num5;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 4. Maestro de Empresas"));
			int num6 = num1;
			num1 = num6 + 1;
			num2 = num6;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 5. Maestro de Divisiones"));
			int num7 = num1;
			num1 = num7 + 1;
			num2 = num7;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 6. Maestro de Empleados"));
			int num8 = num1;
			num1 = num8 + 1;
			num2 = num8;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 7. Maestro Marcas Vehiculos"));
			int num9 = num1;
			num1 = num9 + 1;
			num2 = num9;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 8. Maestro Tipos Vehiculo"));
			int num10 = num1;
			num1 = num10 + 1;
			num2 = num10;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 9. Maestro de Modelos Vehiculo"));
			int num11 = num1;
			num1 = num11 + 1;
			num2 = num11;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 10. Asignacion Vehiculos Empleado"));
			int num12 = num1;
			num1 = num12 + 1;
			num2 = num12;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 11. Maestro de Parqueaderos"));
			int num13 = num1;
			num1 = num13 + 1;
			num2 = num13;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 12. Asignacion de Parqueos"));
			int num14 = num1;
			num1 = num14 + 1;
			num2 = num14;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 13. Maestro de Horarios"));
			int num15 = num1;
			num1 = num15 + 1;
			num2 = num15;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 14. Maestro de Tarjetas"));
			int num16 = num1;
			num1 = num16 + 1;
			num2 = num16;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 15. Visitas Programadas"));
			int num17 = num1;
			num1 = num17 + 1;
			num2 = num17;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 16. Visitantes"));
			int num18 = num1;
			num1 = num18 + 1;
			num2 = num18;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 17. Usuarios"));
			int num19 = num1;
			num1 = num19 + 1;
			num2 = num19;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 18. Roles"));
			int num20 = num1;
			num1 = num20 + 1;
			num2 = num20;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " 19. Liberar Parqueaderos"));
			int num21 = num1;
			num1 = num21 + 1;
			num2 = num21;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num22 = num1;
			num1 = num22 + 1;
			num2 = num22;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num23 = num1;
			num1 = num23 + 1;
			num2 = num23;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num24 = num1;
			num1 = num24 + 1;
			num2 = num24;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num25 = num1;
			num1 = num25 + 1;
			num2 = num25;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num26 = num1;
			num1 = num26 + 1;
			num2 = num26;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num27 = num1;
			num1 = num27 + 1;
			num2 = num27;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num28 = num1;
			num1 = num28 + 1;
			num2 = num28;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num29 = num1;
			num1 = num29 + 1;
			num2 = num29;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num30 = num1;
			num1 = num30 + 1;
			num2 = num30;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num31 = num1;
			num1 = num31 + 1;
			num2 = num31;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num32 = num1;
			num1 = num32 + 1;
			num2 = num32;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num33 = num1;
			num1 = num33 + 1;
			num2 = num33;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num34 = num1;
			num1 = num34 + 1;
			num2 = num34;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num35 = num1;
			num1 = num35 + 1;
			num2 = num35;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num36 = num1;
			num1 = num36 + 1;
			num2 = num36;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num37 = num1;
			num1 = num37 + 1;
			num2 = num37;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num38 = num1;
			num1 = num38 + 1;
			num2 = num38;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num39 = num1;
			num1 = num39 + 1;
			num2 = num39;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num40 = num1;
			num1 = num40 + 1;
			num2 = num40;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num41 = num1;
			num1 = num41 + 1;
			num2 = num41;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num42 = num1;
			num1 = num42 + 1;
			num2 = num42;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num43 = num1;
			num1 = num43 + 1;
			num2 = num43;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num44 = num1;
			num1 = num44 + 1;
			num2 = num44;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num45 = num1;
			num1 = num45 + 1;
			num2 = num45;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num46 = num1;
			num1 = num46 + 1;
			num2 = num46;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num47 = num1;
			num1 = num47 + 1;
			num2 = num47;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num48 = num1;
			num1 = num48 + 1;
			num2 = num48;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num49 = num1;
			num1 = num49 + 1;
			num2 = num49;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num50 = num1;
			num1 = num50 + 1;
			num2 = num50;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			int num51 = num1;
			num1 = num51 + 1;
			num2 = num51;
			this.ListaModulos.Add(string.Concat(num2.ToString(CultureInfo.InvariantCulture), " MODULO SIN ASIGNAR"));
			num1 = 0;
		}
	}
}