using System;

namespace BGCOP.CAVTOP.INNERDEFS
{
	public class Enumeradores
	{
		public Enumeradores()
		{
		}

		public enum ConfiguracaoLeitor
		{
			DESATIVADO,
			ENTRADA,
			SAIDA,
			ENTRADA_SAIDA,
			ENTRADA_SAIDA_INVERTIDA
		}

		public enum Ecoar
		{
			ECOA_DIGITADO,
			ECOA_ASTERISCO
		}

		public enum EntradasMudancaOnline
		{
			NAO_ACEITA_ENTRADA_DADOS = 0,
			ACEITA_TECLADO = 1,
			ACEITA_LEITURA_LEITOR1 = 2,
			ACEITA_LEITURA_LEITOR2 = 3,
			TECLADO_E_LEITOR1 = 4,
			TECLADO_E_LEITOR2 = 5,
			LEITOR1_E_LEITOR2 = 6,
			TECLADO_LEITOR1_LEITOR2 = 7,
			TECLADO_E_VERI_BIOMETRICA = 10,
			LEITOR1_E_VERI_BIOMETRICA = 11,
			TECLADO_E_LEITOR1_E_VERI_BIOMETRICA = 12,
			LEITOR1_E_VERI_BIOMETRICA_LEITOR2_SEM_VERI_BIOMETRICA = 13,
			LEITOR1_E_VERI_BIOMETRICA_LEITOR2_SEM_VERI_BIOMETRICA_E_TECLADO_SEM_VERI_BIOMETRICA = 14,
			LEITOR1_E_IDENTIFICACAO_BIOMETRICA = 100,
			LEITOR1_E_TECLADO_IDENTIFICACAO_BIOMETRICA = 101,
			LEITOR1_E_LEITOR2_E_IDENTIFICACAO_BIOMETRICA = 102,
			LEITOR1_E_LEITOR2_E_TECLADO_E_IDENTIFICACAO_BIOMETRICA = 103,
			LEITOR1_INVERTIDO_IDENTIFICACAO_BIOMETRICA = 104,
			LEITOR1_INVERTIDO_E_TECLADO_E_IDENTIFICACAO_BIOMETRICA = 105
		}

		public enum EstadosInner
		{
			ESTADO_CONECTAR,
			ESTADO_ENVIAR_CFG_OFFLINE,
			ESTADO_COLETAR_BILHETES,
			ESTADO_ENVIAR_CFG_ONLINE,
			ESTADO_ENVIAR_DATA_HORA,
			ESTADO_ENVIAR_MSG_PADRAO,
			ESTADO_CONFIGURAR_ENTRADAS_ONLINE,
			ESTADO_CONFIGURAR_MUDANCAS_ONLINE_OFFLINE,
			ESTADO_POLLING,
			ESTADO_VALIDAR_DADOS,
			ESTADO_LIBERAR_CATRACA,
			ESTADO_ENVIAR_BIPCURTO,
			ESTADO_ENVIAR_MSG_OK,
			ESTADO_LIBERA_GIRO_CATRACA,
			ESTADO_MONITORA_GIRO_CATRACA,
			PING_ONLINE,
			ESTADO_RECONECTAR,
			RECONECTANDO_SERIAL
		}

		public enum FuncaoAcionamento
		{
			NAO_UTILIZADO,
			ACIONA_REGISTRO_ENTRADA_OU_SAIDA,
			ACIONA_REGISTRO_ENTRADA,
			ACIONA_REGISTRO_SAIDA,
			CONECTADO_SIRENE,
			REVISTA_USUARIOS,
			CATRACA_SAIDA_LIBERADA,
			CATRACA_ENTRADA_LIBERADA,
			CATRACA_LIBERADA_DOIS_SENTIDOS,
			CATRACA_LIBERADA_DOIS_SENTIDOS_MARCACAO_REGISTRO
		}

		public enum Habilita
		{
			DESABILITA,
			HABILITA
		}

		public enum MudancaOnlineOffline
		{
			DESABILITA,
			SEM_PING_ONLINE,
			COM_PING_ONLINE
		}

		public enum Opcao
		{
			NAO,
			SIM
		}

		public enum Operacao
		{
			DESATIVADO,
			SOMENTE_ENTRADA,
			SOMENTE_SAIDA,
			ENTRADA_E_SAIDA,
			ENTRADA_E_SAIDA_INVERTIDAS
		}

		public enum Origem
		{
			VIA_TECLADO = 1,
			VIA_LEITOR1 = 2,
			VIA_LEITOR2 = 3,
			SENSOR_DA_CATRACA_OBSOLETO_ = 4,
			FIM_TEMPO_ACIONAMENTO = 5,
			GIRO_DA_CATRACA_TOPDATA = 6,
			URNA = 7,
			EVENTO_SENSOR1 = 8,
			EVENTO_SENSOR2 = 9,
			EVENTO_SENSOR3 = 10,
			SENSOR_BIOMETRICO = 12,
			TECLA_CONFIRMA = 35,
			PRESENCA_DEDO = 37,
			TECLA_ANULA = 42,
			TECLA_FUNCAO = 65,
			TECLA_ENTRADA = 66,
			TECLA_SAIDA = 67
		}

		public enum PadraoCartao
		{
			PADRAO_TOPDATA,
			PADRAO_LIVRE
		}

		public enum Retorno
		{
			RET_COMANDO_OK = 0,
			RET_COMANDO_ERRO = 1,
			RET_PORTA_NAO_ABERTA = 2,
			RET_PORTA_JA_ABERTA = 3,
			RET_DLL_INNER2K_NAO_ENCONTRADA = 4,
			RET_DLL_INNERTCP_NAO_ENCONTRADA = 5,
			RET_DLL_INNERTCP2_NAO_ENCONTRADA = 6,
			RET_ERRO_GPF = 8,
			RET_TIPO_CONEXAO_INVALIDA = 9
		}

		public enum RetornoBIO
		{
			FALHA_NA_COMUNICACAO = 1,
			PROCESSANDO_ULTIMO_COMANDO = 128,
			FALHA_NA_COMUNICACAO_COM_PLACA_BIO = 129,
			INNER_BIO_NAO_ESTA_EM_MODO_MASTER = 130,
			USUARIO_JA_CADASTRADO_NO_BANCO_DE_DADOS_INNER_BIO = 131,
			USUARIO_NAO_CADASTRADO_NO_BANCO_DE_DADOS_INNER_BIO = 132,
			BASE_DE_DADOS_DE_USUARIOS_ESTA_CHEIA = 133,
			ERRO_NO_SEGUNDO_DEDO_DO_USUARIO = 134,
			SOLICITACAO_PARA_INNER_BIO_INVALIDA = 135
		}

		public enum TipoConexao
		{
			SERIAL_RS232_485,
			TCP_IP_COM_PORTA_VARIAVEL,
			TCP_IP_COM_PORTA_FIXA,
			MODEM,
			TOP_PENDRIVE
		}

		public enum TipoLeitor
		{
			CODIGO_DE_BARRAS,
			MAGNETICO,
			PROXIMIDADE_ABATRACK2,
			WIEGAND,
			PROXIMIDADE_SMART_CARD
		}
	}
}